### ISSUE TITLE
Nothing happens when pressing anything

### ISSUE THREAD

**Issue by Postremus** [dhood/pullrequest-visualiser#1]
Hey,

I just found out about this project at @pjf 's twitter.

http://dhood.github.io/pullrequest-visualiser/plot.html?KSP-CKAN/CKAN
I pressed on the button "Show all Events", nothing happens in edge and in chrome.
The gui also says "Showing 0 / 0 events (zoomable) ".
Are I am doing anything wrong?

I took a quick look into the Browsers console, found a 404:

```
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.(XHR): GET - https://api.github.com/repos/KSP-CKAN/CKAN//undefined/pulls?state=all&page=1&direction=desc&sort=created&per_page=100
```

Seems the problem is the "CKAN//undefined"

greetings
postremus

**Comment by dhood** [comment]
Thanks for reporting @Postremus! Can you confirm it's fixed now, please?

**Comment by Postremus** [comment]
fixed, thank you. :+1:

**Comment by dhood** [comment]
Thanks a lot!
