### ISSUE TITLE
Rendering is blurry in edge

### ISSUE THREAD

**Issue by Postremus** [dhood/pullrequest-visualiser#2]
hey,

the graph is a bit blurry in edge:
![ss 2015-08-19 at 05 39 50](https://cloud.githubusercontent.com/assets/1223135/9360941/6ee51eb2-4699-11e5-983a-e76b5be18af0.png)

for comparison, how it looks in Chrome:
![ss 2015-08-19 at 05 39 29](https://cloud.githubusercontent.com/assets/1223135/9360997/aaa0ef30-4699-11e5-9d60-f158b0224a78.png)

greetings,
postremus

**Comment by dhood** [comment]
Hi @Postremus, thanks for the heads up. I'm not sure if it's related to some [others'](http://www.tenforums.com/general-discussion/7423-blurry-text-4.html) issues with blurry fonts, but I'll have to leave this up to CanvasJS to fix, otherwise. Sorry about that!

**Comment by Postremus** [comment]
Thank you for your Investigation.

**Comment by dhood** [comment]
Thanks for the report!
